### PR TITLE
nuget via lib file instead of manual install

### PR DESCRIPTION
**Pull request by paulstelzer**
With lib-file the nuget package will be added to Cordova Windows automatically, no nuget package manager is needed

### CODE REVIEW

**Comment by victorsosa** [comment]
thanks, will be in next release

**Comment by paulstelzer** [comment]
Wow, you are fast :)

**Comment by paulstelzer** [comment]
@victorsosa can you revert this commit? It seems that this isn't working very well on PCs, who do not have this package installed. So it will fail.

**Comment by victorsosa** [comment]
ok

**Pull request merged**
