### PR TITLE
Browser platform added

### PR DESCRIPTION
**Pull request by mlegenhausen**
This pull request should be a good starting point for integrating the browser platform.

The current implementation is a simple development mock for printing the currently cordova.exec calls to the browser debug console.

### CODE REVIEW

**Comment by victorsosa** [comment]
Thanks, please also check the issue #53 

I will keep this on hold until I can check how to complete this start point.

**Comment by victorsosa** [comment]
This is the GA api documentation this may help to complete the code:
https://developers.google.com/analytics/devguides/collection/analyticsjs/

**Comment by mlegenhausen** [comment]
I have added google analaytics support for the browser platform.

Following issues needs to be discussed:

 * [ ] Should the `hitCallback` be integrated for all `send` commands.
   * https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#hitCallback
 * [ ] We need the `appName` for current enabling app tracking in the browser. This is really complicated currently with corodva. The current approach uses the `document.title` as `appName`.
 * [ ] `trackView` does not support the `campaingUrl` parameter. Any known alternative for known?

**Comment by victorsosa** [comment]
Awesome job... I will check the issue and come back to you

**Comment by mlegenhausen** [comment]
There will be bugs, didn't found the time to test it yet.

**Comment by victorsosa** [comment]
Should the hitCallback be integrated for all send commands. - Yes, it should be the success callback function to the proxy call to do that.

    https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#hitCallback

We need the appName for current enabling app tracking in the browser. This is really complicated 
currently with corodva. The current approach uses the document.title as appName. - For now it will be fine, but a new method or parameter would be a solution. Keep it as is for now.

trackView does not support the campaingUrl parameter. Any known alternative?- Just ignore the parameter for this platform.

Some documentation need to be added to the readme about the new API.

As soon you finish development and test the new API, let me know to complete the PR.

**Comment by mlegenhausen** [comment]
This code is now working and solves the problems suggested above. This plugin also loads the `analaytics.js` from google in a async way. People who want to use the plugin in a website that has already integrated google analytics needs to make sure that they remove the google analytics snippet from the head section of the page and change the global `ga` object name to something else. The plugin uses `nativeGa` instead. This can be changed by the follow code.

```
// insert this in your head
<script>
window['GoogleAnalyticsObject'] = 'fooGa';
</script>
```

The plugin will pick up the new name.

**Comment by victorsosa** [comment]
Thanks, could you please document this is the readme?. Create a section just to describe this new platform. :tada: :+1:  awesome job

**Comment by victorsosa** [comment]
Thanks, I will update the readme file

**Pull request merged**
