### PR TITLE
added possibility to unset custom dimension/metric

### PR DESCRIPTION
**Pull request by spacepope**
As pointed out in https://github.com/danwilson/google-analytics-plugin/issues/415 the custom dimensions and metrics could not be unset.
This is now possible via passing null or an empty string for value parameter in addCustomDimension or omit the value paramter in trackMetric.

Tested in Android emulator with debugMode with this code:
```javascript
public test() {
    this.platform.ready().then(() => {
      return this.ga.startTrackerWithId("UA-xxxxxxxx-x");
    }).then(() => {
      return this.ga.debugMode();
    }).then(() => {
      return this.ga.setAnonymizeIp(true);
    }).then(() => {
      return this.ga.enableUncaughtExceptionReporting(true);
    }).then(() => {
      return this.ga.addCustomDimension(1, "MyDimension");
    }).then(() => {
      // in Ionic 2 one has to currently use string formatted key
      return this.ga.trackMetric("1", 12.23);
    }).then(() => {
      return this.ga.trackView("HomePage");
    }).then(() => {
      return this.ga.trackEvent("HomePage", "AnalyticsInitialized", JSON.stringify(this.platform.platforms()));
    }).then(() => {
      return this.ga.trackTiming("HomePage", 1234, "InitDuration", "Timing");
    }).then(() => {
      return this.ga.trackException("You Fail!", false);
    }).then(() => {
      // unset dimension
      return this.ga.addCustomDimension(1, "");
    }).then(() => {
     // in Ionic 2 one has to currently use string formatted key
     // unset metric
      return this.ga.trackMetric("1");
    }).then(() => {
      return this.ga.trackEvent("HomePage", "UnsetCustomDimensionAndMetric");
    }).catch((err) => {
      console.error(err);
    });
  }
```

Echoe response from Google:
```
07-13 06:15:58.198 I/GAv4    ( 3724): Dry run enabled. Would have sent hit: ht=1499926558197, _v=ma11.0.20, a=61755579, aid=io.ionic.starter, aip=1, an=MyApp, av=0.0.1, cd=HomePage, cd1=MyDimension, cid=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx, cm1=12.23, sr=1080x1794, t=screenview, tid=UA-xxxxxxxx-x, ul=en-us, v=1
07-13 06:15:58.199 I/GAv4    ( 3724): Dry run enabled. Would have sent hit: ht=1499926558198, _v=ma11.0.20, a=61755580, aid=io.ionic.starter, aip=1, an=MyApp, av=0.0.1, cd=HomePage, cd1=MyDimension, cid=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx, cm1=12.23, ea=AnalyticsInitialized, ec=HomePage, el=["cordova","mobile","android","phablet"], ev=0, sr=1080x1794, t=event, tid=UA-xxxxxxxx-x, ul=en-us, v=1
07-13 06:15:58.200 I/GAv4    ( 3724): Dry run enabled. Would have sent hit: ht=1499926558200, _v=ma11.0.20, a=61755580, aid=io.ionic.starter, aip=1, an=MyApp, av=0.0.1, cd=HomePage, cd1=MyDimension, cid=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx, cm1=12.23, sr=1080x1794, t=timing, tid=UA-xxxxxxxx-x, ul=en-us, utc=HomePage, utl=Timing, utt=1234, utv=InitDuration, v=1
07-13 06:15:58.201 I/GAv4    ( 3724): Dry run enabled. Would have sent hit: ht=1499926558201, _v=ma11.0.20, a=61755580, aid=io.ionic.starter, aip=1, an=MyApp, av=0.0.1, cd=HomePage, cd1=MyDimension, cid=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx, cm1=12.23, exd=You Fail!, exf=0, sr=1080x1794, t=exception, tid=UA-xxxxxxxx-x, ul=en-us, v=1
07-13 06:15:58.208 I/GAv4    ( 3724): Dry run enabled. Would have sent hit: ht=1499926558207, _v=ma11.0.20, a=61755580, aid=io.ionic.starter, aip=1, an=MyApp, av=0.0.1, cd=HomePage, cid=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx, ea=UnsetCustomDimensionAndMetric, ec=HomePage, el=, ev=0, sr=1080x1794, t=event, tid=UA-xxxxxxxx-x, ul=en-us, v=1
```

In the last hit data no more custom dimension and metric is tracked..

### CODE REVIEW

**Comment by spacepope** [comment]
Just noticed that most changed lines in the Android java file are no _functional_ code changes but only automatic formatting of VS Code.
Sorry for that..

**Comment by spacepope** [comment]
@victorsosa, regarding the discussion in https://github.com/danwilson/google-analytics-plugin/issues/441 
should a call to `trackView(.., .., true)` (with starting a new session) clear the internal dictionaries?

**Comment by victorsosa** [comment]
@spacepope That is a great idea; in that way there is no need to clean the dictionary by calling:
`this.ga.addCustomDimension(1, "");`

**Comment by victorsosa** [comment]
Let me know when you finish; so I can merge this PR.

**Comment by spacepope** [comment]
Yeah, at first glance it looks promising/tempting, but there could be one downside:
if one wants to track a view while starting a new session AND change a custom dimension, this could lead to unwanted behaviour, as one has to either set the dimension before the trackView() which results in clearing the dimension before it actually gets transmitted (and get lost so far), or set it after the trackView() which would send the new dimension not until the subsequent hit is tracked..

If we dont't implement this auto-reset feature, one could change the custom dimension before the `trackView(.., .., true)` and the new dimension is sent with the view hit on the new session.
Also - and perhaps important? - one could decide to clear a specific dimension/metric only and keep the others on f.e. user scope..

What's your opinion on this?

**Comment by victorsosa** [comment]
Good catch; we shouldn't implement this auto-reset feature, let's keep as the PR is.

**Comment by spacepope** [comment]
Then i am finished with this PR.
Should we wait, if/until @Sollll has tested this as proposed in https://github.com/danwilson/google-analytics-plugin/issues/441?

**Comment by spacepope** [comment]
But you could also merge and tell him to test again from your repo..

**Comment by victorsosa** [comment]
thanks, awesome work

**Pull request merged**
