### PR TITLE
[fixes #55] added support for enableAdvertisingIdCollection(boolean) 

### LINKED ISSUE #55: How can we enable Google Analytics Demographics and Interest Reports
When going into Google Analytics Demographics and Interest Reports I get a message that my tracking code does not provide the necesary support for the Demographics and Interest Reports.

### PR DESCRIPTION
**Pull request by mediavrog**
PR for https://github.com/danwilson/google-analytics-plugin/issues/55 to support display advertisement features as described in https://support.google.com/analytics/answer/2444872.

Please check the IOS part, since I never touched any IOS project before. Also, what else would be needed to get started with this? The docs stated something about:

> To use Google Analytics advertising features requires that you collect the IDFA (Identifier for Advertisers). To enable IDFA collection, link the libAdIdAccess.a and AdSupport.framework libraries to your application and set the allowIDFACollection property to YES on each tracker for which you want to enable advertising features.

I added the `libAdIdAccess.a` manually in the XCode build, and it seemingly works. I will have to verify with data after another 24 hours. Is there any way to add this file automatically during build?

### CODE REVIEW

**Comment by yongyu-lee** [comment]
Awesome!!! Thank you ...

[LGTM](http://www.lgtm.in/i/qzZEIZw1q)

[:+1:](http://www.lgtm.in/u/qzZEIZw1q) [:-1:](http://www.lgtm.in/r/qzZEIZw1q)

**Comment by danwilson** [comment]
Thanks! I plan to verify the changes as soon as I have a free moment...

**Comment by mediavrog** [comment]
@danwilson Thanks for the feedback.

Actually, I don't think the plugin should include this file automatically, because not everyone might want to include the Demographics tracking (I read Apple checks usage of this feature especially). Is there way for conditional inclusion?

**Comment by danwilson** [comment]
Very good point... I will research the best way to handle that.  I know there are also command line options you can enable to be specified when a user adds the plugin... will need to see if that suits this case.

**Comment by Ballrock** [comment]
Unless I am mistaken, the method enableAdvertisingIdCollection() is not present in the Tracker class of  libGoogleAnalyticsServices.jar... unlike google-play-services.jar...

So, merge that pull request on my fork generates "Cannot find symbol" errors at compilation.

**Comment by mediavrog** [comment]
@Ballrock Loocks like this method was added in SDKL version 4, so I guess the library needs to be updated (https://developers.google.com/analytics/devguides/collection/android/v4/#tracking-methods)

**Comment by Ballrock** [comment]
So we can maybe get the lib from import *Google Play service* for Android via SDK Manager.

I don't know if it's standalone but i've got the *google-play-service.jar* with the needed method at `sdk\extras\google\google_play_services\libproject\google-play-services_lib\libs`

But  it seems that we need a little work to adapt the plugin to this new library.

**Comment by danwilson** [comment]
I thought that might be the case with this feature... I am going to create a new issue to update to google play services for android... Which will involve modifying all the calls. We will get that in first and then circle back to this. Thanks!

**Comment by Ballrock** [comment]
So i watched at it a little.
It seems that update the code to V4 is quite easy with the JAR, i currently testing a new version in my fork. 
More details e737f0e977288d430ae71f4d57354bb5517a2bf5

**Comment by mediavrog** [comment]
Android update PR see https://github.com/danwilson/google-analytics-plugin/pull/67

**Comment by Ballrock** [comment]
Now that # 67 is merged we can return to this PR ; )

**Comment by felquis** [comment]
Awesome guys :dancer: 

Any news `enableAdvertisingIdCollection`?

**Comment by Ballrock** [comment]
I did some internals testing about this function after #67, it seems that it not work as expected :disappointed: Someone else tried ?

**Comment by zwacky** [comment]
+1

this is exactly what i am looking for. any more infos?

**Comment by vlaraort** [comment]
I am also looking for this functionality, are there any news? I tryied with the Ballrock solution but it gives "Invalid action" in console when trying to do enableAdvertisingIdCollection

**Comment by dkellycollins** [comment]
Is there any news on this? I'm looking to add this feature to my app.

**Comment by vanstinator** [comment]
Looking for this as well. @danwilson any chance this can get looked at again?

**Comment by chemerisuk** [comment]
According to the [docs](https://developers.google.com/analytics/devguides/collection/ios/v3/campaigns#troubleshoot-idfa), you also need to link `AdSupport.framework` as well. Does it make sense?

**Comment by cmarrero01** [comment]
This bug it will be solve?.. I have this problem with my implementation of this plugin.

**Comment by vomchik** [comment]
any updates?

**Comment by victorsosa** [comment]
@mediavrog can you please fix the conflicts? to merge this as soon as possible.

**Comment by victorsosa** [comment]
@mediavrog can you please fix the conflicts?

**Comment by Ballrock** [comment]
I think this need some tests before any thinking about merge...
I did some of them, last year, that has not been very successful. 
On the other hand, I dont have enough userbase in my apps to see if it really work or not.

**Comment by victorsosa** [comment]
This was already merged #252

**Pull request closed without merging**
