### PR TITLE
TypeScript Definition Created

### PR DESCRIPTION
**Pull request by bohtm4711**
TypeScript Definition Created for Google Analytics plugin, with all
functions defined

### CODE REVIEW

**Comment by victorsosa** [comment]
@bohtm4711 Awesome, I will put you PR in hold because I had some new methods added to the interface, so I want you to update you PR with those new methods. Stay tuned

**Comment by victorsosa** [comment]
added trackMetric #204; please add this method to the definition.

**Comment by bohtm4711** [comment]
Done :-)

**Comment by victorsosa** [comment]
Thank you :+1:

**Pull request merged**
