### PR TITLE
Fix custom metric

### PR DESCRIPTION
**Pull request by ogoguel**

### CODE REVIEW

**Comment by victorsosa** [comment]
Thanks

**Comment by victorsosa** [comment]
I just double check with the DOC:
https://developers.google.com/analytics/devguides/collection/ios/v3/customdimsmets

And the first parameter seems to be a number; so how this is a fix?? can you explain it?

**Comment by ogoguel** [comment]
The first parameter (key) must be an int, hence the explicit conversion from NSNumber to int
The second parameter (value) must be a string hence the conversion from NSNumber to string

Without that fix, the key sent to GoogleAnalytics was the adress of the key itself (ie: the NSNumber object) , and not its value

Actually, the error was properly detected by XCode which complained about the improper conversions

**Comment by victorsosa** [comment]
Thanks for explain the issue.

**Pull request merged**
