### PR TITLE
(feature) Run tracking activites in background thread

### PR DESCRIPTION
**Pull request by DomiR**
Added "runInBackground" to most tasks that interface with the tracker instance.

Refactoring of #155

### CODE REVIEW

**Comment by cmarrero01** [comment]
Hi @DomiR I install the plugin from your repo, and I see that still happen the same problem.

THREAD WARNING: ['UniversalAnalytics'] took '10.616943' ms. Plugin should use a background thread.

**Comment by victorsosa** [comment]
@DomiR please update you branch; so we can merge this; Thanks

**Comment by victorsosa** [comment]
@DomiR can you please fix the conflicts? to merge this as soon as possible.

**Comment by victorsosa** [comment]
Refactoring of #155 was merged; thanks

**Pull request closed without merging**
