### PR TITLE
Add campaign measurement tracking

### LINKED ISSUE #68: Google Campaign Measurement Available?
I have a phonegap based app, looking to integrate with a google marketing campaign.
From google's website: https://developers.google.com/analytics/devguides/collection/ios/v3/campaigns it says there are some steps that need to be taken to the native sdk code to make campaigns work.  Has this been integrated at all?  Is it in the works?  On hold?  I'm evaluating either going the native route or sticking with this plugin.

### PR DESCRIPTION
**Pull request by joshdover**
Fixes #68

### CODE REVIEW

**Comment by bwalsh** [comment]
+1 would love to get this via phonegap build

**Comment by vipulkrsingh** [comment]
@danwilson is there something that can be done ( or something i can help with .. )  to get this merged ?

/cc @joshdover

**Comment by engincancan** [comment]
+1 for this. Android already works afaik but is there current option for ios

**Comment by victorsosa** [comment]
@joshdover can you please fix the conflicts? to merge this as soon as possible.

**Comment by victorsosa** [comment]
using PR #264

**Pull request closed without merging**
