### PR TITLE
Added Windows 10 (UWP) Support

### PR DESCRIPTION
**Pull request by spacepope**
Hi,

i added support for windows platform (Windows 10 UWP) to the google-analytics-plugin.
I implemented a proxy for the [Microsoft Windows SDK for Google Analytics](https://github.com/dotnet/windows-sdk-for-google-analytics).
As for the win8 support one has to manually install the SDK via the Visual Studio nuget package manager (see revised readme).

A few methods are currently not supported (also see revised readme, last paragraph).

Would be nice if someone else can try this and see if it's working as expected..

Regards,
Hannes

### CODE REVIEW

**Comment by victorsosa** [comment]
Awesome work; I will check this out asap

**Comment by victorsosa** [comment]
This looks good to go, merged

**Comment by spacepope** [comment]
Wow, that was fast ;)
So looking forward to see some feedback from others targeting Windows 10 UWP..
👍

**Comment by victorsosa** [comment]
target for next release

**Comment by spacepope** [comment]
damn, just noticed a small typo in the readme:

> Unexpected behaviour **my** occur on the following methods

should rather be:
> Unexpected behaviour **may** occur on the following methods

seems pretty heavy to open another pull request just for this - can you fix this at the next opportunity?

**Comment by victorsosa** [comment]
don't worry I will fix it

**Pull request merged**
