### PR TITLE
Change CustomDimension from String to Int in iOS

### PR DESCRIPTION
**Pull request by martyzz1**
Should hopefully fix some crash reports I've been seeing

### CODE REVIEW

**Comment by victorsosa** [comment]
@martyzz1 can you please made the fix for the method trackMetric too?

**Comment by martyzz1** [comment]
Ok, I made the change, but not able to test it. Looks straightforward enough though

**Comment by martyzz1** [comment]
ok tested this, seems to compile and work ok now

**Comment by victorsosa** [comment]
Thanks @martyzz1 you are awesome

**Pull request merged**
