### PR TITLE
new variable GMS_VERSION

### PR DESCRIPTION
**Pull request by cvaliere**

### CODE REVIEW

**Comment by cvaliere** [comment]
please?

**Comment by cvaliere** [comment]
ping

**Comment by lowderl** [comment]
Currently experience issues with conflicting versions of google play services due to this plugin. It is very frustrating. I really don't want to have to manually edit my build.gradle. This change should be made.

**Comment by victorsosa** [comment]
merge for 1.8.4 release

**Comment by lowderl** [comment]
Thanks so much!

**Comment by lowderl** [comment]
@victorsosa Thank you for these changes. We just bumped our version of the plugin and specified the api version and it's working as expected! Sorry if I was a bit harsh above, I had been trying to troubleshoot this problem for a while. 

Thanks again, and really appreciate your efforts!

**Pull request merged**
