### PR TITLE
Background thread execution in iOS

### PR DESCRIPTION
**Pull request by tsanidas**
Added "runInBackground" to most tasks that interface with the tracker instance.

### CODE REVIEW

**Comment by tsanidas** [comment]
I think my local messed with line endings and/or indents, so I apologize for that.

**Comment by stephanebachelier** [comment]
@tsanidas you should remove all these extra spaces. It would be more consistent and help seeing what you've done :)

**Comment by cmarrero01** [comment]
This PR is ok for merge? If so, I think this is related to my problem... 

THREAD WARNING: ['UniversalAnalytics'] took '12.389160' ms. Plugin should use a background thread.

If this help to solve this problema, I will install the plugin from your github repo.

**Comment by tsanidas** [comment]
I am not sure I fixed the file line endings, so it would appear as though I changed every line.  Let me look at this.  Otherwise, this has worked for me in my project for months now.

**Comment by victorsosa** [comment]
@tsanidas can you please fix the conflicts? to merge this as soon as possible.

**Comment by victorsosa** [comment]
@tsanidas can you please fix the conflicts? to merge this as soon as possible.

**Comment by victorsosa** [comment]
This was manually merged.

**Pull request closed without merging**
